### PR TITLE
Jgleoj23 branch

### PR DESCRIPTION
**Pull request by jogardi**
I made it automatically compile native js modules. I haven't added any configuration options yet but I put the options that are used by the java compiler into the js compiler. The maven invoker plugin doesn't work on my machine so I commented it out. I wasn't able to figure out how to get it working.

### CODE REVIEW

**Comment by jogardi** [comment]
I'm wandering why you haven't accepted the pull request. It's fine if you just haven't gotten around to it but if you haven't accepted it because there is an issue with the code, just tell me what the issue is and I'll try to fix it.

**Comment by quintesse** [comment]
Let's tag @vietj directly, just to be sure he reads this.

**Comment by thradec** [comment]
@jgleoj23 did you copy whole ceylon-js compiler into ceylon-maven-plugin?

**Comment by vietj** [comment]
I don't get why this PR has 230 files changed, can you clean the PR or make another PR to keep only the necessary changes ?

**Comment by jogardi** [comment]
I had to get the code for compiling JavaScript. I think the best way to do
that would be to put that code I a repository and include it as a maven
dependency. A more straightforward approach would be to write code that
installs the ceylon command line and uses the command line to compile
JavaScript.

**Comment by quintesse** [comment]
Closing, this PR is superseded by 5a74a61

**Pull request closed without merging**
